spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <client-id>
            clientSecret: <client-secret>
            scope: read:user, user:email